version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@10
workflows:
  deploy:
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          filters:
            branches:
              only: master
          orb-name: coryzibell/cloudflare-wrangler
          publish-version-tag: false
  pack:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              only: develop
      - orb-tools/pack:
          filters:
            branches:
              only: develop
      - orb-tools/publish-dev:
          filters:
            branches:
              only: develop
          orb-name: coryzibell/cloudflare-wrangler
          requires:
            - orb-tools/lint
            - orb-tools/pack