version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@10
workflows:
  pack_deploy:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: coryzibell/cloudflare-wrangler
          alpha-version-ref: dev:<< pipeline.git.branch >>
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/dev-promote-prod-from-git-tag:
          add-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/
          orb-name: coryzibell/cloudflare-wrangler
          requires:
            - orb-tools/lint
            - orb-tools/pack